In [2]:
x = "Mukul"
print("Hi {} Saini".format(x))

Hi Mukul Saini


In [3]:
print(x[:4])

Muku


In [7]:
l1 = list(range(0, 10, 2))

In [8]:
l1

[0, 2, 4, 6, 8]

In [9]:
l1.sort(reverse = True)

In [10]:
print(l1)

[8, 6, 4, 2, 0]


In [13]:
print(l1[0])

8


In [15]:
days = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
print(days[2])

Wednesday


In [19]:
import numpy as np
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(c)
print(type(c))

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
<class 'numpy.ndarray'>


In [20]:
arr1 = np.array([1, 2, 3, 5])
print(arr1)

[1 2 3 5]


In [21]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [22]:
c.shape

(2, 2, 3)

In [24]:
c.dtype

dtype('float64')

In [32]:
rand_arr = np.random.random((2,2)) 

In [33]:
rand_arr

array([[0.11070429, 0.79078463],
       [0.1660105 , 0.30871956]])

In [29]:
rand_arr1 = np.random.rand(2,2)

In [30]:
rand_arr1

array([[0.53803724, 0.10068351],
       [0.51624758, 0.86836691]])

In [34]:
rand_arr2 = np.random.randn(2,2)

In [35]:
rand_arr2

array([[-0.27181709,  1.03606798],
       [-0.50600797, -0.16021226]])

In [37]:
arr2 = np.diag([1,2,3])

In [38]:
arr2

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [3]:
import numpy as np
arr3 = np.diag =([0,0,0])

In [4]:
arr3

[0, 0, 0]